blank_issues_enabled: true
contact_links:
  - name: Download MYCAM v1.0
    url: https://github.com/elementtime6969/mycam/raw/main/downloads/Mycam-v1.0.apk
    about: Download the current official APK.
