blank_issues_enabled: true
contact_links:
  - name: Download MYCAM v2.9.18
    url: https://github.com/elementtime6969/mycam/raw/main/downloads/Mycam-v2.9.18.apk
    about: Download the current official APK.
